name: 'andrei-action-prototype'
description: 'Greet someone and record the time'
inputs:
  token:
    description: 'Token'
    required: true
outputs:
  checkRunId:
    description: 'The check run id that was generated'
runs:
  using: 'node12'
  main: 'index.js'
